from __future__ import annotations
from collections.abc import Callable, Iterable, Iterator, Mapping
from typing import Any, TYPE_CHECKING, Literal, get_origin, get_args
import sys
import warnings
from beartype import beartype
from beartype.door import is_bearable
from .trails import fo, dual_property, dual_method, classmethod_only
from .constants import (
    Sentinel, MISSING_ARG, ABSENT, DNA_SYMBOL,
    STATIC, DYNAMIC, BLUEPRINTS, ON_EXTRA_KWARGS_CREATE,
    ON_EXTRA_KWARGS_RAISE,)
from .exceptions import (
    CobConstraintViolationError, GrainTypeMismatchError,
    CobConsistencyError, SchemaViolationError, DataBarnSyntaxError)
from .grain import BaseGrain, create_grain_class

if TYPE_CHECKING:
    from .cob import Cob
    from .barn import Barn

_type = type  # Alias to avoid confusion with the 'type' attribute in BaseGrain

# @beartype
class BaseDna:
    """Internal metadata/behavior container shared by Cob models and instances.

    The class-level view stores model metadata (grains, labels, constraints).
    The instance-level view stores per-cob runtime state (grains, barn links,
    parent links, mapping-like helpers).
    """

    @staticmethod
    def _type_display_name(type_hint: Any) -> str:
        """Return a user-facing type name for error messages."""
        if isinstance(type_hint, _type):
            return type_hint.__name__
        forward_arg = getattr(type_hint, "__forward_arg__", None)
        if isinstance(forward_arg, str):
            return forward_arg
        if isinstance(type_hint, str):
            return type_hint
        return str(type_hint)

    @staticmethod
    def _barn_model_matches(expected_model_type: Any, actual_model_type: _type[Any]) -> bool:
        """Compare Barn model type args while tolerating unresolved forward references."""
        if isinstance(expected_model_type, _type):
            return actual_model_type is expected_model_type
        expected_name = BaseDna._type_display_name(expected_model_type)
        expected_short_name = expected_name.split(".")[-1]
        return actual_model_type.__name__ == expected_short_name

    @staticmethod
    def _resolve_type_hint(type_hint: Any, model: _type[Cob]) -> Any:
        """Resolve string annotations against the model module when possible."""
        if not isinstance(type_hint, str):
            return type_hint
        module = sys.modules.get(model.__module__)
        globalns = dict(vars(module)) if module is not None else {}
        globalns[model.__name__] = model
        globalns.setdefault("__builtins__", __builtins__)
        try:
            return eval(type_hint, globalns, globalns)
        except Exception:
            return type_hint

    # Model
    model: _type[Cob]
    label_grain_map: dict[str, _type[BaseGrain] |
                          BaseGrain]  # {label: grain or grainob}
    # This is an ordered set of all Cob instances of this model.
    # Used for consistency cascading updates.
    cobs: list[Cob]
    blueprint: Literal[*BLUEPRINTS]
    on_extra_kwargs: str
    # This is set by relationship decorators to link back to the
    # synthetic grain they generate for the outer model.
    _outer_model_grain: _type[BaseGrain] | None = None

    # Cob instance
    cob: Cob  # type: ignore
    autoid: int  # If the primakey is not provided, autoid will be used as primakey
    barns: list[Barn]
    _container_parent_map: dict[BaseGrain | Barn, Cob]  # Map of grain objects to their parent cobs

    @classmethod
    # Set by decorators
    def _set_outer_model_grain(klass, outer_model_grain: _type[BaseGrain]) -> None:
        """Store the synthetic grain generated by relationship decorators."""
        klass._outer_model_grain = outer_model_grain

    @classmethod_only
    def _embed_grain(klass, label: str, grain: _type[BaseGrain]) -> None:
        """Register a grain under `label` in the Cob-model or Cob instance.

        Args:
            grain: type[BaseGrain] or BaseGrain object to register.
            label: Attribute name for the grain.
        """
        if label in klass.labels:
            raise CobConsistencyError(fo(f"""
                The Grain '{label}' has already been
                set up in this {klass}."""))
        grain._validate()
        klass.label_grain_map[label] = grain  # type: ignore

    @classmethod_only
    def create_barn(klass) -> Barn:  # type: ignore
        """Create a new Barn for the model.

        Returns:
            A new Barn object for the model.
        """
        from .barn import Barn  # Lazy import to avoid circular imports
        return Barn(model=klass.model)

    @classmethod_only
    def create_cob_from_dict(klass,
                             dikt: dict,
                             replace_space_with: str | None = "_",
                             replace_dash_with: str | None = "__",
                             suffix_keyword_with: str | None = "_",
                             prefix_leading_num_with: str | None = "n_",
                             replace_invalid_char_with: str | None = "_",
                             suffix_existing_attr_with: str | None = "_",
                             # type: ignore
                             custom_key_converter: Callable[[Any], str] | None = None) -> Cob:
        """Create a Cob instance from a dictionary.

        Args:
            dikt: The dictionary to convert to a Cob.
            replace_space_with: Replace spaces in keys with this string.
            replace_dash_with: Replace dashes in keys with this string.
            suffix_keyword_with: Suffix keywords with this string.
            prefix_leading_num_with: Prefix leading numbers in keys with this string.
            replace_invalid_char_with: Replace invalid characters in keys with this string.
            suffix_existing_attr_with: Suffix existing attributes with this string.
            custom_key_converter: A custom function to convert keys.
        Returns:
            A new Cob instance bound to this model.
        """
        from .funcs import dict_to_cob  # Lazy import to avoid circular imports
        cob = dict_to_cob(
            dikt,
            model=klass.model,
            replace_space_with=replace_space_with,
            replace_dash_with=replace_dash_with,
            suffix_keyword_with=suffix_keyword_with,
            prefix_leading_num_with=prefix_leading_num_with,
            replace_invalid_char_with=replace_invalid_char_with,
            suffix_existing_attr_with=suffix_existing_attr_with,
            custom_key_converter=custom_key_converter,)
        return cob

    @classmethod_only
    def create_cob_from_json(klass,
                             json_str: str,
                             replace_space_with: str | None = "_",
                             replace_dash_with: str | None = "__",
                             suffix_keyword_with: str | None = "_",
                             prefix_leading_num_with: str | None = "n_",
                             replace_invalid_char_with: str | None = "_",
                             suffix_existing_attr_with: str | None = "_",
                             custom_key_converter: Callable[[
                                 Any], str] | None = None,
                             **json_loads_kwargs) -> Cob:  # type: ignore
        """Create a Cob instance from JSON text.

        Args:
            json_str: The JSON string to convert to a Cob.
            replace_space_with: Replace spaces in keys with this string.
            replace_dash_with: Replace dashes in keys with this string.
            suffix_keyword_with: Suffix keywords with this string.
            prefix_leading_num_with: Prefix leading numbers in keys with this string.
            replace_invalid_char_with: Replace invalid characters in keys with this string.
            suffix_existing_attr_with: Suffix existing attributes with this string.
            custom_key_converter: A custom function to convert keys.
            **json_loads_kwargs:
                Additional keyword arguments to pass to ``json.loads``.

        Returns:
            A new Cob instance bound to this model.
        """
        from .funcs import json_to_cob  # Lazy import to avoid circular imports
        cob = json_to_cob(
            json_str=json_str,
            model=klass.model,
            replace_space_with=replace_space_with,
            replace_dash_with=replace_dash_with,
            suffix_keyword_with=suffix_keyword_with,
            prefix_leading_num_with=prefix_leading_num_with,
            replace_invalid_char_with=replace_invalid_char_with,
            suffix_existing_attr_with=suffix_existing_attr_with,
            custom_key_converter=custom_key_converter,
            **json_loads_kwargs)
        return cob

    @dual_property
    def grains(owner) -> tuple[type[BaseGrain], ...]:
        """Return a tuple of the grains of the model or cob."""
        return tuple(owner.label_grain_map.values())

    @dual_property
    def labels(owner) -> tuple[str, ...]:
        """Return a tuple of the labels of the model or cob."""
        return tuple(owner.label_grain_map.keys())

    @dual_property
    def primakey_labels(owner) -> tuple[str, ...]:
        """Return a tuple of the primakey labels of the model or cob."""
        labels = [grain.label for grain in owner.grains if grain.pk]
        return tuple(labels)

    @dual_property
    def primakey_defined(owner) -> bool:
        """Return True if the primakey is defined for the model or cob."""
        return (len(owner.primakey_labels) > 0)

    @dual_property
    def is_compos_primakey(owner) -> bool:
        """Return whether the model uses a composite primary key."""
        return (len(owner.primakey_labels) > 1)

    @dual_property
    def primakey_len(owner) -> int:
        """Return number of primary key grains, or ``1`` when none are defined."""
        return (len(owner.primakey_labels) or 1)

    @dual_method
    def get_grain(owner, label: str, default: Any = MISSING_ARG) -> _type[BaseGrain] | Any:
        """Return the model grain registered under ``label``.

        Args:
            label: The Grain label.
            default: Value to return when the label does not exist.

        Returns:
            The matching Grain, or ``default`` when provided and missing.
        """
        if default is MISSING_ARG and label not in owner.labels:
            raise KeyError(fo(f"""
                The Grain '{label}' does not exist in the model '{owner.model.__name__}'."""))
        return owner.label_grain_map.get(label, default)

    @property
    def active_grains(self) -> tuple[BaseGrain, ...]:
        """Return a tuple of Cob's grains whose values have been set and not been deleted."""
        grains = [grain for grain in self.grains if grain.attr_exists()]
        return tuple(grains)

    @property
    def primakey_grains(self) -> tuple[BaseGrain, ...]:
        """Return a tuple of the Cob's primakey grains."""
        return tuple(self.get_grain(label) for label in self.primakey_labels)

    @property
    def parents(self) -> tuple[Cob, ...]:
        """Return a tuple of parent cobs that currently contain this cob."""
        return tuple(self._container_parent_map.values())

    @property
    def latest_parent(self) -> Cob | None:  # type: ignore
        """Return the latest parent cob if exists, otherwise None.

        CAUTION: If the cob has multiple parents, only the last one is returned.
        """
        if not self.parents:
            return None
        return self.parents[-1]

    # Cob object methods
    def __init__(self, cob: Cob) -> None:  # type: ignore
        """Initialize runtime DNA state for a concrete Cob instance."""
        self.cob = cob
        self.autoid = id(cob)  # Default autoid is the id of the cob object
        # Register this cob in the model's catalog
        self.cobs.append(cob)
        self.barns = []
        self._container_parent_map = {}
        self.label_grain_map = {}  # Instance-level grainobs
        # Use the class-level grains here
        for grain in self.__class__.grains:
            grainob = grain(cob)
            # Use the instance-level embedding method
            # to register the grainob in the cob's dna
            self._embed_grainob(grain.label, grainob)

    def _add_barn(self, barn: Barn) -> None:  # type: ignore
        """Register a Barn that currently contains this Cob."""
        self.barns.append(barn)

    def _remove_barn(self, barn: Barn) -> None:  # type: ignore
        """Unregister a Barn that no longer contains this Cob."""
        self.barns.remove(barn)

    def _embed_grainob(self, label: str, grainob: BaseGrain) -> None:
        """Embed a Grain object in the Cob instance under `label`."""
        if label in self.label_grain_map:
            raise CobConsistencyError(fo(f"""
                The Grain '{label}' has already been
                set up in this Cob instance."""))
        self.label_grain_map[label] = grainob

    def dyn_add_grain(self, label: str, type: Any = Any) -> BaseGrain:
        """Add a grain to the Cob instance at runtime.

        Args:
            label: The grain label.
            type: The grain type.

        Returns:
            The added grain instance.
        """
        if self.blueprint != DYNAMIC:
            raise SchemaViolationError(fo(f"""
                Cannot insert Grain '{label}', because this Cob
                '{self.model.__name__}' has been defined by
                blueprint '{self.blueprint}'."""))
        grain = create_grain_class()
        grain.__setup__(parent_model=self.model, label=label, type=type)
        grainob = grain(self.cob)
        self._embed_grainob(label, grainob)
        return grainob

    def _dyn_remove_grain(self, label: str) -> None:
        """Remove a grain from the Cob instance at runtime.

        Args:
            label: The grain label to remove.
        """
        if self.blueprint != DYNAMIC:
            raise SchemaViolationError(fo(f"""
                Cannot remove the Grain '{label}' because this Cob
                '{self.model.__name__}' has been defined by
                blueprint '{self.blueprint}'."""))
        if label not in self.label_grain_map:
            raise KeyError(fo(f"""
                Cannot remove the Grain '{label}', because it
                does not exist in the cob."""))
        del self.label_grain_map[label]

    def get_keyring(self) -> Any | tuple[Any, ...] | Sentinel:
        """Return the key used by Barn lookups for this Cob.

        If no primary key is defined, ``autoid`` is used.

        Returns:
            Primary key value, composite key tuple, or `ABSENT` when a declared
            primary key grain is currently unset.
        """
        if not self.primakey_defined:
            return self.autoid
        primakeys = []
        for grain in self.primakey_grains:
            if not grain.attr_exists():
                return ABSENT
            primakeys.append(grain.get_value())
        if not self.is_compos_primakey:
            return primakeys[0]
        return tuple(primakeys)

    def _verify_constraints(self, grain: BaseGrain, value: Any) -> None:
        """Validate type and constraint rules before assigning ``value`` to ``grain``.

        Args:
            grain: Target grain.
            value: Candidate value to assign.
        """
        resolved_type = self._resolve_type_hint(grain.type, self.model)
        if resolved_type is not Any:
            bearable = False
            try:
                bearable = is_bearable(value, resolved_type)
            except Exception as exc:
                # Postponed/quoted forward references can fail to resolve in beartype.
                # Keep DataBarn's exception surface stable for callers.
                from .barn import Barn  # Lazy import to avoid circular imports
                if isinstance(value, Barn):
                    expected_model_type = None
                    origin_type = get_origin(resolved_type)
                    if origin_type is Barn:
                        type_args = get_args(resolved_type)
                        if type_args:
                            expected_model_type = type_args[0]
                    else:
                        type_name = self._type_display_name(resolved_type)
                        if type_name.startswith("Barn[") and type_name.endswith("]"):
                            expected_model_name = type_name[5:-
                                                            1].strip().strip("'\"")
                            if value.model.__name__ == expected_model_name:
                                bearable = True
                    if expected_model_type is not None and self._barn_model_matches(expected_model_type, value.model):
                        bearable = True
                if not bearable:
                    raise GrainTypeMismatchError(fo(f"""
                        Cannot assign '{grain.label}={value}' because the Grain
                        type '{resolved_type}' could not be resolved ({exc.__class__.__name__}).""")) from exc
            if not bearable:
                raise GrainTypeMismatchError(fo(f"""
                    Cannot assign '{grain.label}={value}' because the Grain
                    was defined as {resolved_type}, but got {type(value)}."""))
            from .barn import Barn  # Lazy import to avoid circular imports
            origin_type = get_origin(resolved_type)
            if origin_type is Barn:
                type_args = get_args(resolved_type)
                if type_args:
                    expected_model_type = type_args[0]
                    if not self._barn_model_matches(expected_model_type, value.model):
                        expected_model_name = self._type_display_name(
                            expected_model_type)
                        raise GrainTypeMismatchError(fo(f"""
                            Cannot assign '{grain.label}={value}' because the Grain
                            was defined as 'Barn[{expected_model_name}]',
                            but got 'Barn[{value.model.__name__}]'."""))
        if grain.frozen and grain.attr_exists():
            raise CobConstraintViolationError(fo(f"""
                Cannot assign '{grain.label}={value}' because the Grain
                was defined as 'frozen=True'."""))
        if grain.pk and self.barns:
            raise CobConstraintViolationError(fo(f"""
                Cannot assign '{grain.label}={value}' because the Grain
                was defined as 'pk=True' and the Cob has been added to a barn."""))
        if grain.unique and self.barns:
            for barn in self.barns:
                barn._check_uniqueness_by_value(grain, value)

    def _add_parent(self, container: BaseGrain | Barn, parent: Cob) -> None:
        """Register a parent Cob reference."""
        self._container_parent_map[container] = parent

    def _remove_parent(self, container: BaseGrain | Barn) -> None:
        """Remove a parent Cob reference."""
        del self._container_parent_map[container]

    def _set_parent_for_new_value_if(self, grainob: BaseGrain):
        """Attach this cob as parent when assigning child Cob/Barn values."""
        # Lazy import to avoid circular imports
        from .barn import Barn
        from .cob import Cob
        value = grainob.get_value()
        if isinstance(value, Barn):
            child_barn = value  # Just for clarity
            child_barn._add_parent_cob(self.cob)
        elif isinstance(value, Cob):
            child_cob = value  # Just for clarity
            child_cob.__dna__._add_parent(grainob, self.cob)

    def _remove_parent_if(self, grain: BaseGrain) -> None:
        """Detach parent links for previous child Cob/Barn values when replaced."""
        # Lazy import to avoid circular imports
        from .barn import Barn
        from .cob import Cob
        # First assignment has no previous value to detach.
        if not grain.attr_exists():
            return
        value = grain.get_value()
        if isinstance(value, Barn):
            child_barn = value  # Just for clarity
            # Remove the parent for the barn
            child_barn._remove_parent_cob(self.cob)
        elif isinstance(value, Cob):
            child_cob = value  # Just for clarity
            child_cob.__dna__._remove_parent(grain)

    def _check_and_get_comparables(self, cob: Cob, strict: bool = True) -> list[BaseGrain]:
        """Validate comparison compatibility and return comparable grains."""
        if not isinstance(cob, self.model):
            if strict:
                raise CobConsistencyError(fo(f"""
                    Cannot compare this Cob '{self.model.__name__}' with
                    '{type(cob).__name__}', because they are different types."""))
            return []
        comparables = [grain for grain in self.grains if grain.comparable]
        if not comparables and strict:
            raise CobConstraintViolationError(fo(f"""
                Cannot compare Cob '{self.model.__name__}' with '{type(cob).__name__}'
                because they have no comparable grains in common. To enable comparison,
                set comparable=True on at least one grain in the Cob-model."""))
        return comparables

    # dict-like methods
    def items(self) -> Iterator[tuple[str, Any]]:
        """Yield ``(label, value)`` for active grains."""
        for grain in self.active_grains:
            yield grain.label, grain.get_value()

    def keys(self) -> Iterator[str]:
        """Yield labels of active grains."""
        for grain in self.active_grains:
            yield grain.label

    def clear(self) -> None:
        """Remove all values from the cob."""
        for grain in self.active_grains:
            del self.cob[grain.label]

    # def copy(self) -> Cob:  # type: ignore
    #     """Create a shallow copy of the Cob."""
    #     raise NotImplementedError(fo(f"""
    #         The 'copy' method is not implemented yet for Cob objects."""))

    # def fromkeys(self, seq: Sequence[str], value: Any) -> Cob:
    #     """That function that no one uses."""
    #     dikt: dict[str, Any] = {}
    #     for key in seq:
    #         dikt[key] = value
    #     return self.model(**dikt)

    def get(self, key: str, default: Any = MISSING_ARG) -> Any:
        """Return value for ``key`` if present, else ``default``.

        If ``default`` is omitted and the key is unknown, model-level validation
        may raise an error.
        """
        grain = self.get_grain(key, default=None)
        if default is MISSING_ARG and grain is None:
            raise KeyError(fo(f"""
                The key '{key}' does not exist in the Cob '{self.model.__name__}'."""))
        if grain is None or not grain.attr_exists():
            return default
        return grain.get_value()

    def pop(self, key: str, default: Any = MISSING_ARG) -> Any:
        """Remove ``key`` and return its value.

        Args:
            key: The Grain label to remove.
            default: Fallback value when key does not exist.
        """
        if key in self.labels:
            value = self.cob[key]
            del self.cob[key]
            return value
        if default is MISSING_ARG:
            raise KeyError(fo(f"""
                The key '{key}' does not exist in the cob."""))
        return default

    def popitem(self) -> tuple[str, Any]:
        """Removes the key and value of last defined Grain.

        Returns:
            A tuple of (key, value) of the removed attribute.
            Raises KeyError if the Cob is empty.
        """
        if not self.active_grains:
            raise KeyError(
                fo(f"""The Cob '{self.model.__name__}' is empty."""))
        last_grain = self.active_grains[-1]
        value = last_grain.get_value()  # Get value before deletion
        del self.cob[last_grain.label]
        return last_grain.label, value

    def setdefault(self, key: str, default: Any) -> Any:
        """Return existing value for ``key`` or store and return ``default``."""
        grain = self.get_grain(key, default=None)
        if grain and grain.attr_exists():
            return grain.get_value()
        self.cob[key] = default
        return default

    def update(self, other: Mapping[str, Any] | \
               Iterable[tuple[Any, Any]] | \
               Sentinel = MISSING_ARG,
               /, **kwargs: Any) -> None:
        """Update multiple values from a mapping/iterable and keyword pairs."""
        if other is not MISSING_ARG:
            if type(other) is dict:
                for key in other.keys():
                    self.cob[key] = other[key]
            else:
                for key, value in other:
                    self.cob[key] = value
        for key, value in kwargs.items():
            self.cob[key] = value

    def values(self) -> Iterator[Any]:
        """Yield values of active grains."""
        for grain in self.active_grains:
            yield grain.get_value()

    def to_dict(self) -> dict[str, Any]:
        """Create a dictionary out of the cob.

        Every sub-Barn is converted into a list of cobs,
        which are then converted to dictionaries recursively.
        Every sub-cob is converted to a dictionary too.
        If key is set for a grain, it is used as the key instead of the label.

        Returns:
            A dictionary representation of the cob
        """
        # Lazy import to avoid circular imports
        from .barn import Barn
        from .cob import Cob
        key_value_map = {}
        for grain in self.grains:
            key = grain.key or grain.label
            grain_value = grain.get_value(default=ABSENT)
            if grain_value is ABSENT:
                continue  # Skip unset values
            # If value is a barn, recursively process its cobs
            if isinstance(grain_value, Barn):
                barn = grain_value
                dicts = [cob.__dna__.to_dict() for cob in barn]
                key_value_map[key] = dicts
            # Elif value is a cob, convert it to a dict
            elif isinstance(grain_value, Cob):
                key_value_map[key] = grain_value.__dna__.to_dict()
            # Recursively process lists and tuples
            elif isinstance(grain_value, (list, tuple)):
                new_list = []
                for item in grain_value:
                    if isinstance(item, Cob):
                        new_list.append(item.__dna__.to_dict())
                    elif isinstance(item, Barn):
                        new_list.append([cob.__dna__.to_dict()
                                        for cob in item])
                    else:
                        new_list.append(item)
                collection_type: _type[list[Any]] | _type[tuple[Any, ...]] = type(
                    grain_value)
                key_value_map[key] = collection_type(new_list)
            else:
                key_value_map[key] = grain_value
        return key_value_map

    def to_json(self, **json_dumps_kwargs) -> str:
        """Serialize this Cob to JSON via :meth:`to_dict`.

        Every sub-Barn is converted into a list of cobs,
        which are then converted to dictionaries recursively.
        Every sub-cob is converted to a dictionary too.

        Args:
            **json_dumps_kwargs:
                Additional keyword arguments to pass to json.dumps().

        Returns:
            JSON string representation of the cob.
        """
        import json  # lazy import to avoid unecessary computation
        return json.dumps(self.to_dict(), **json_dumps_kwargs)


def create_dna_class(model: _type[Cob]) -> _type[BaseDna]:
    """Create and initialize a dedicated DNA subclass for the Cob-model."""
    annotations = dict(getattr(model, "__annotations__", {}))
    relationship_grains: dict[str, _type[BaseGrain]] = {}

    # Normalize relationship-generated grains and validate model declarations.
    for symbol, value in list(model.__dict__.items()):
        if symbol == DNA_SYMBOL:
            raise DataBarnSyntaxError(fo(f"""
                Cannot use protected attribute name '{symbol}'
                in Cob-model '{model.__name__}'."""))
        sub_dna = getattr(value, DNA_SYMBOL, None)
        if isinstance(sub_dna, _type) and issubclass(sub_dna, BaseDna):
            if sub_dna._outer_model_grain:
                grain = sub_dna._outer_model_grain
                relationship_grains[grain.label] = grain
                annotations[grain.label] = grain.type

    for symbol, value in model.__dict__.items():
        if isinstance(value, _type) and issubclass(value, BaseGrain) and symbol not in annotations:
            raise DataBarnSyntaxError(fo(f"""
                Missing type annotation for Grain '{symbol}' in Cob-model '{model.__name__}'.
                Use typing.Any if unsure of the type."""))

    class Dna(BaseDna):
        pass

    Dna.model = model
    Dna.cobs = []
    Dna.label_grain_map = {}
    for label, type_hint in annotations.items():
        if label in relationship_grains:
            grain = relationship_grains[label]
        else:
            value: _type[BaseGrain] | Any = getattr(model, label, ABSENT)
            if value is ABSENT:
                grain = create_grain_class()
            elif isinstance(value, _type) and issubclass(value, BaseGrain):
                grain = value
            else:
                grain = create_grain_class(default=value)
        grain.__setup__(parent_model=model, label=label, type=type_hint)
        Dna._embed_grain(label, grain)
    Dna.blueprint = STATIC if Dna.label_grain_map else DYNAMIC
    Dna.on_extra_kwargs = (
        ON_EXTRA_KWARGS_CREATE if Dna.blueprint == DYNAMIC else ON_EXTRA_KWARGS_RAISE)
    return Dna
