from __future__ import annotations
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from types import MappingProxyType
from typing import Any, TYPE_CHECKING, get_origin, get_args
from types import SimpleNamespace 
from beartype.door import is_bearable
from beartype.roar import BeartypeDecorHintForwardRefException
from .trails import fo, dual_property, dual_method, classmethod_only, Catalog
from .constants import Sentinel, ABSENT
from .exceptions import CobConstraintViolationError, GrainTypeMismatchError, CobConsistencyError, StaticModelViolationError, DataBarnViolationError, DataBarnSyntaxError
from .grain import BaseGrain, create_grain_class

if TYPE_CHECKING:
    from .cob import Cob
    from .barn import Barn


class BaseDna:
    """Internal metadata/behavior container shared by Cob models and instances.

    The class-level view stores model metadata (grains, labels, constraints).
    The instance-level view stores per-cob runtime state (grists, barn links,
    parent links, mapping-like helpers).
    """

    @staticmethod
    def _type_display_name(type_hint: Any) -> str:
        """Return a user-facing type name for error messages."""
        if isinstance(type_hint, type):
            return type_hint.__name__
        forward_arg = getattr(type_hint, "__forward_arg__", None)
        if isinstance(forward_arg, str):
            return forward_arg
        if isinstance(type_hint, str):
            return type_hint
        return str(type_hint)

    @staticmethod
    def _barn_model_matches(expected_model_type: Any, actual_model_type: type[Any]) -> bool:
        """Compare Barn model type args while tolerating unresolved forward references."""
        if isinstance(expected_model_type, type):
            return actual_model_type is expected_model_type
        expected_name = BaseDna._type_display_name(expected_model_type)
        expected_short_name = expected_name.split(".")[-1]
        return actual_model_type.__name__ == expected_short_name

    # Model
    model: type["Cob"]
    label_grain_map: Mapping[str, type[BaseGrain]]  # {label: type[BaseGrain]}
    dynamic: bool
    # Changed by the one_to_many_grain decorator
    _outer_model_grain: type[BaseGrain] | None = None

    # Cob instance
    cob: "Cob"  # type: ignore
    autoid: int  # If the primakey is not provided, autoid will be used as primakey
    barns: Catalog["Barn"]  # type: ignore # This is an ordered set of Barns
    label_grist_map: dict[str, type[BaseGrain]] | Mapping[str, BaseGrain]  # {label: BaseGrain}
    parents: Catalog  # Catalog[Cob] is an ordered set of parent Cobs

    @classmethod
    def __setup__(klass, model: type["Cob"]) -> None:
        """Initialize class-level metadata for a Cob model.

        Args:
            model: Cob subclass whose annotations and defaults define grains.
        """
        klass.model = model
        klass.label_grain_map = {}
        annotations: dict[str, Any] = getattr(model, "__annotations__", {})
        for label, type in annotations.items():
            attr_value: type[BaseGrain] | Any = getattr(model, label, ABSENT)
            if attr_value is ABSENT:
                grain = create_grain_class()
            elif issubclass(attr_value, BaseGrain):
                grain = attr_value
            else:
                grain = create_grain_class(default=attr_value)
            klass._setup_and_embed_grain(grain, label, type)
        klass.dynamic = False if klass.label_grain_map else True
        # Make the label_grain_map read-only (either dynamic or static model)
        klass.label_grain_map = MappingProxyType(klass.label_grain_map)

    @classmethod
    # Set by decorators
    def _set_outer_model_grain(klass, outer_model_grain: type[BaseGrain]) -> None:
        """Store the synthetic grain generated by relationship decorators."""
        klass._outer_model_grain = outer_model_grain

    @dual_method
    def _validate_grain(owner, grain: type[BaseGrain]) -> None:
        """Validate grain-level invariants before embedding it into the model."""
        if grain.autoenum and not issubclass(grain.type, int):  # type: ignore
            raise DataBarnSyntaxError(fo(f"""
                The BaseGrain '{grain.label}' was defined as 'autoenum=True',
                but was type annotated as {grain.type}.
                'autoenum' only works with 'int' or compatible types."""))

    @dual_method
    def _setup_and_embed_grain(owner, grain: type[BaseGrain], label: str, type: Any) -> None:
        """Attach model metadata to a grain and register it under ``label``.

        Args:
            grain: type[BaseGrain] object to register.
            label: Attribute name for the grain.
            type: Type annotation declared for the grain.
        """
        if label in owner.labels:
            raise CobConsistencyError(fo(f"""
                The BaseGrain '{label}' has already been
                set up in {owner}.label_grain_map."""))
        grain._set_parent_model_metadata(
            parent_model=owner.model, label=label, type=type)
        owner._validate_grain(grain)
        owner.label_grain_map[label] = grain  # type: ignore

    @classmethod_only
    def create_barn(klass) -> "Barn":  # type: ignore
        """Create a new Barn for the model.

        Returns:
            A new Barn object for the model.
        """
        from .barn import Barn  # Lazy import to avoid circular imports
        return Barn(model=klass.model)

    @classmethod_only
    def create_cob_from_dict(klass,
                             dikt: dict,
                             replace_space_with: str | None = "_",
                             replace_dash_with: str | None = "__",
                             suffix_keyword_with: str | None = "_",
                             prefix_leading_num_with: str | None = "n_",
                             replace_invalid_char_with: str | None = "_",
                             suffix_existing_attr_with: str | None = "_",
                             # type: ignore
                             custom_key_converter: Callable[[Any], str] | None = None) -> "Cob":
        """Create a Cob instance from a dictionary.

        Args:
            dikt: The dictionary to convert to a Cob.
            replace_space_with: Replace spaces in keys with this string.
            replace_dash_with: Replace dashes in keys with this string.
            suffix_keyword_with: Suffix keywords with this string.
            prefix_leading_num_with: Prefix leading numbers in keys with this string.
            replace_invalid_char_with: Replace invalid characters in keys with this string.
            suffix_existing_attr_with: Suffix existing attributes with this string.
            custom_key_converter: A custom function to convert keys.
        Returns:
            A new Cob instance bound to this model.
        """
        from .funcs import dict_to_cob  # Lazy import to avoid circular imports
        cob = dict_to_cob(
            dikt,
            model=klass.model,
            replace_space_with=replace_space_with,
            replace_dash_with=replace_dash_with,
            suffix_keyword_with=suffix_keyword_with,
            prefix_leading_num_with=prefix_leading_num_with,
            replace_invalid_char_with=replace_invalid_char_with,
            suffix_existing_attr_with=suffix_existing_attr_with,
            custom_key_converter=custom_key_converter,)
        return cob

    @classmethod_only
    def create_cob_from_json(klass,
                             json_str: str,
                             replace_space_with: str | None = "_",
                             replace_dash_with: str | None = "__",
                             suffix_keyword_with: str | None = "_",
                             prefix_leading_num_with: str | None = "n_",
                             replace_invalid_char_with: str | None = "_",
                             suffix_existing_attr_with: str | None = "_",
                             custom_key_converter: Callable[[
                                 Any], str] | None = None,
                             **json_loads_kwargs) -> "Cob":  # type: ignore
        """Create a Cob instance from JSON text.

        Args:
            json_str: The JSON string to convert to a Cob.
            replace_space_with: Replace spaces in keys with this string.
            replace_dash_with: Replace dashes in keys with this string.
            suffix_keyword_with: Suffix keywords with this string.
            prefix_leading_num_with: Prefix leading numbers in keys with this string.
            replace_invalid_char_with: Replace invalid characters in keys with this string.
            suffix_existing_attr_with: Suffix existing attributes with this string.
            custom_key_converter: A custom function to convert keys.
            **json_loads_kwargs:
                Additional keyword arguments to pass to ``json.loads``.

        Returns:
            A new Cob instance bound to this model.
        """
        from .funcs import json_to_cob  # Lazy import to avoid circular imports
        cob = json_to_cob(
            json_str=json_str,
            model=klass.model,
            replace_space_with=replace_space_with,
            replace_dash_with=replace_dash_with,
            suffix_keyword_with=suffix_keyword_with,
            prefix_leading_num_with=prefix_leading_num_with,
            replace_invalid_char_with=replace_invalid_char_with,
            suffix_existing_attr_with=suffix_existing_attr_with,
            custom_key_converter=custom_key_converter,
            **json_loads_kwargs)
        return cob

    @dual_property
    def grains(owner) -> tuple[type[BaseGrain], ...]:
        """Return a tuple of the grains of the model or cob."""
        return tuple(owner.label_grain_map.values())

    @dual_property
    def labels(owner) -> tuple[str, ...]:
        """Return a tuple of the labels of the model or cob."""
        return tuple(owner.label_grain_map.keys())

    @dual_property
    def primakey_labels(owner) -> tuple[str, ...]:
        """Return a tuple of the primakey labels of the model or cob."""
        labels = [grain.label for grain in owner.grains if grain.pk]
        return tuple(labels)

    @dual_property
    def primakey_defined(owner) -> bool:
        """Return True if the primakey is defined for the model or cob."""
        return (len(owner.primakey_labels) > 0)

    @dual_property
    def is_compos_primakey(owner) -> bool:
        """Return whether the model uses a composite primary key."""
        return (len(owner.primakey_labels) > 1)

    @dual_property
    def primakey_len(owner) -> int:
        """Return number of primary key grains, or ``1`` when none are defined."""
        return (len(owner.primakey_labels) or 1)

    @dual_method
    def get_grain(owner, label: str, default: Any = ABSENT) -> type[BaseGrain] | Any:
        """Return the model grain registered under ``label``.

        Args:
            label: BaseGrain label.
            default: Value to return when the label does not exist.

        Returns:
            The matching BaseGrain, or ``default`` when provided and missing.
        """
        if default is ABSENT and label not in owner.label_grain_map:
            raise DataBarnViolationError(fo(f"""
                The BaseGrain '{label}' does not exist in the model '{owner.model.__name__}'."""))
        return owner.label_grain_map.get(label, default)

    # Cob object methods
    def __init__(self, cob: "Cob") -> None:  # type: ignore
        """Initialize runtime DNA state for a concrete Cob instance."""
        self.cob = cob
        self.autoid = id(cob)  # Default autoid is the id of the cob object
        self.barns = Catalog()
        self.parents = Catalog()
        if self.dynamic:
            # If the model is dynamic, the object-level label_grain_map
            # must be different from the class-level
            self.label_grain_map = {}
        self.label_grist_map = {}
        for grain in self.grains:
            self._create_and_embed_grist(grain)
        if not self.dynamic:
            # Make the label_grist_map read-only (static cob)
            self.label_grist_map = MappingProxyType(self.label_grist_map)

    @property
    def grists(self) -> tuple[BaseGrain, ...]:
        """Return a tuple of Cob's grists."""
        return tuple(self.label_grist_map.values())

    @property
    def active_grists(self) -> tuple[BaseGrain, ...]:
        """Return a tuple of Cob's grists whose values have been set and not been deleted."""
        grists = [grist for grist in self.grists if grist.attr_exists()]
        return tuple(grists)

    @property
    def primakey_grists(self) -> tuple[BaseGrain, ...]:
        """Return a tuple of the Cob's primakey grists."""
        return tuple(self.get_grist(label) for label in self.primakey_labels)

    @property
    def latest_parent(self) -> "Cob" | None:  # type: ignore
        """Return the latest parent cob if exists, otherwise None.

        CAUTION: If the cob has multiple parents, only the last one is returned.
        """
        if not self.parents:
            return None
        return self.parents[-1]

    def get_grist(self, label: str, default: Any = ABSENT) -> BaseGrain | Any:
        """Returns the grist for the given label.
        If default is not provided and the label does not exist, raises error.
        Otherwise, returns the default."""
        if default is ABSENT and label not in self.label_grist_map:
            raise DataBarnViolationError(fo(f"""
                The Grist '{label}' does not exist in the Cob '{self.model.__name__}'."""))
        return self.label_grist_map.get(label, default)

    def _create_and_embed_grist(self, grain: type[BaseGrain]) -> BaseGrain:
        """Create and register a Grist bound to this Cob for ``grain``."""
        if grain not in self.grains:
            raise CobConsistencyError(fo(f"""
                Cannot create a Grist for the BaseGrain '{grain.label}' because
                it does not exist in the model '{self.model.__name__}'."""))
        if grain.label in self.label_grist_map:
            raise CobConsistencyError(fo(f"""
                Cannot create a Grist for the BaseGrain '{grain.label}' because
                it has already been created in the Cob '{self.model.__name__}'."""))
        grist = grain(self.cob)
        self.label_grist_map[grist.label] = grist
        return grist

    def _create_cereals_dynamically(self, label: str,
                                    type: Any = Any,
                                    grain: type[BaseGrain] | None = None) -> SimpleNamespace:
        """Create and register a dynamic BaseGrain plus matching Grist.

        Args:
            label: Label for the dynamic grain.
            type: Type annotation for the dynamic grain.
            grain: Optional pre-built BaseGrain object to reuse.

        Returns:
            A namespace containing both created objects: ``grain`` and ``grist``.
        """
        if not self.dynamic:
            raise StaticModelViolationError(fo(f"""
                Cannot create the grain '{label}', because the Cob-model is static.
                It is considered static, because at least one grain has been defined
                in the model. Therefore, dynamic grain creation is not allowed."""))
        if label in self.labels:
            raise CobConsistencyError(fo(f"""
                Cannot create the BaseGrain '{label}', because it
                has already been created before."""))
        if grain is None:
            grain = create_grain_class()
        self._setup_and_embed_grain(grain, label, type)
        grist = self._create_and_embed_grist(grain)
        return SimpleNamespace(grain=grain, grist=grist)

    def add_grain_dynamically(self, label: str, type: Any, grain: type[BaseGrain]) -> None:
        """Add a custom BaseGrain to a dynamic model at runtime.

        Args:
            label: Label for the new grain.
            type: Type annotation for the grain.
            grain: BaseGrain object to register.
        """
        self._create_cereals_dynamically(label, type, grain)

    def _remove_cereals_dynamically(self, label: str) -> None:
        """Remove a dynamic BaseGrain and its Grist from this cob.

        Args:
            label: Label of the grain to remove.
        """
        if not self.dynamic:
            raise StaticModelViolationError(fo(f"""
                Cannot remove the BaseGrain '{label}' because the Cob-model
                is static and does not allow dynamic BaseGrain deletion."""))
        if label not in self.labels:
            raise KeyError(fo(f"""
                Cannot remove the BaseGrain '{label}', because it
                does not exist in the model."""))
        del self.label_grist_map[label]
        del self.label_grain_map[label]

    def _add_barn(self, barn: "Barn") -> None:  # type: ignore
        """Register a Barn that currently contains this Cob."""
        self.barns.add(barn)

    def _remove_barn(self, barn: "Barn") -> None:  # type: ignore
        """Unregister a Barn that no longer contains this Cob."""
        self.barns.remove(barn)

    def get_keyring(self) -> Any | tuple[Any, ...] | Sentinel:
        """Return the key used by Barn lookups for this Cob.

        If no primary key is defined, ``autoid`` is used.

        Returns:
            Primary key value, composite key tuple, or ``ABSENT`` when a declared
            primary key grain is currently unset.
        """
        if not self.primakey_defined:
            return self.autoid
        primakeys = []
        for grist in self.primakey_grists:
            if not grist.attr_exists():
                return ABSENT
            primakeys.append(grist.get_value())
        if not self.is_compos_primakey:
            return primakeys[0]
        return tuple(primakeys)

    def to_dict(self) -> dict[str, Any]:
        """Create a dictionary out of the cob.

        Every sub-Barn is converted into a list of cobs,
        which are then converted to dictionaries recursively.
        Every sub-cob is converted to a dictionary too.
        If key is set for a grain, it is used as the key instead of the label.

        Returns:
            A dictionary representation of the cob
        """
        # Lazy import to avoid circular imports
        from .barn import Barn
        from .cob import Cob
        key_value_map = {}
        for grist in self.grists:
            key = grist.key or grist.label
            grist_value = grist.get_value(default=ABSENT)
            if grist_value is ABSENT:
                continue  # Skip unset values
            # If value is a barn, recursively process its cobs
            if isinstance(grist_value, Barn):
                barn = grist_value
                dicts = [cob.__dna__.to_dict() for cob in barn]
                key_value_map[key] = dicts
            # Elif value is a cob, convert it to a dict
            elif isinstance(grist_value, Cob):
                key_value_map[key] = grist_value.__dna__.to_dict()
            # Recursively process lists and tuples
            elif isinstance(grist_value, (list, tuple)):
                new_list = []
                for item in grist_value:
                    if isinstance(item, Cob):
                        new_list.append(item.__dna__.to_dict())
                    elif isinstance(item, Barn):
                        new_list.append([cob.__dna__.to_dict()
                                        for cob in item])
                    else:
                        new_list.append(item)
                collection_type: type[list[Any]] | type[tuple[Any, ...]] = type(
                    grist_value)
                key_value_map[key] = collection_type(new_list)
            else:
                key_value_map[key] = grist_value
        return key_value_map

    def to_json(self, **json_dumps_kwargs) -> str:
        """Serialize this Cob to JSON via :meth:`to_dict`.

        Every sub-Barn is converted into a list of cobs,
        which are then converted to dictionaries recursively.
        Every sub-cob is converted to a dictionary too.

        Args:
            **json_dumps_kwargs:
                Additional keyword arguments to pass to json.dumps().

        Returns:
            JSON string representation of the cob.
        """
        import json  # lazy import to avoid unecessary computation
        return json.dumps(self.to_dict(), **json_dumps_kwargs)

    def _verify_constraints(self, grist: BaseGrain, value: Any) -> None:
        """Validate type and constraint rules before assigning ``value`` to ``grist``.

        Args:
            grist: Target grist.
            value: Candidate value to assign.
        """
        if grist.type is not Any:
            bearable = False
            try:
                bearable = is_bearable(value, grist.type)
            except BeartypeDecorHintForwardRefException as exc:
                # Postponed/quoted forward references can fail to resolve in beartype.
                # Keep DataBarn's exception surface stable for callers.
                from .barn import Barn  # Lazy import to avoid circular imports
                if get_origin(grist.type) is Barn and isinstance(value, Barn):
                    bearable = True
                else:
                    raise GrainTypeMismatchError(fo(f"""
                        Cannot assign '{grist.label}={value}' because the BaseGrain
                        type '{grist.type}' could not be resolved ({exc.__class__.__name__}).""")) from exc
            if not bearable:
                raise GrainTypeMismatchError(fo(f"""
                    Cannot assign '{grist.label}={value}' because the BaseGrain
                    was defined as {grist.type}, but got {type(value)}."""))
            from .barn import Barn  # Lazy import to avoid circular imports
            origin_type = get_origin(grist.type)
            if origin_type is Barn:
                type_args = get_args(grist.type)
                if type_args:
                    expected_model_type = type_args[0]
                    if not self._barn_model_matches(expected_model_type, value.model):
                        expected_model_name = self._type_display_name(
                            expected_model_type)
                        raise GrainTypeMismatchError(fo(f"""
                            Cannot assign '{grist.label}={value}' because the BaseGrain
                            was defined as 'Barn[{expected_model_name}]',
                            but got 'Barn[{value.model.__name__}]'."""))
        if grist.frozen and grist.attr_exists():
            raise CobConstraintViolationError(fo(f"""
                Cannot assign '{grist.label}={value}' because the BaseGrain
                was defined as 'frozen=True'."""))
        if grist.pk and self.barns:
            raise CobConstraintViolationError(fo(f"""
                Cannot assign '{grist.label}={value}' because the BaseGrain
                was defined as 'pk=True' and the Cob has been added to a barn."""))
        if grist.unique and self.barns:
            for barn in self.barns:
                barn._check_uniqueness_by_value(grist, value)

    def _add_parent(self, parent: "Cob") -> None:
        """Register a parent Cob reference."""
        self.parents.add(parent)

    def _remove_parent(self, parent: "Cob") -> None:
        """Remove a parent Cob reference."""
        self.parents.remove(parent)

    def _set_parent_for_new_value_if(self, grist: BaseGrain):
        """Attach this cob as parent when assigning child Cob/Barn values."""
        # Lazy import to avoid circular imports
        from .barn import Barn
        from .cob import Cob
        value = grist.get_value()
        if isinstance(value, Barn):
            child_barn = value  # Just for clarity
            child_barn._add_parent_cob(self.cob)
        elif isinstance(value, Cob):
            child_cob = value  # Just for clarity
            child_cob.__dna__._add_parent(self.cob)

    def _remove_prev_value_parent_if(self, grist: BaseGrain, new_value: Any) -> None:
        """Detach parent links for previous child Cob/Barn values when replaced."""
        if not grist.attr_exists() or grist.get_value() is new_value:
            return  # No previous value or no change
        # Lazy import to avoid circular imports
        from .barn import Barn
        from .cob import Cob
        old_value = grist.get_value()
        if isinstance(old_value, Barn):
            child_barn = old_value  # Just for clarity
            # Remove the parent for the barn
            child_barn._remove_parent_cob(self.cob)
        elif isinstance(old_value, Cob):
            child_cob = old_value  # Just for clarity
            child_cob.__dna__._remove_parent(self.cob)

    def _check_and_get_comparables(self, cob: "Cob") -> list[BaseGrain]:
        """Validate comparison compatibility and return comparable grists."""
        if not isinstance(cob, self.model):
            raise CobConsistencyError(fo(f"""
                Cannot compare this Cob '{self.model.__name__}' with
                '{type(cob).__name__}', because they are different types."""))
        comparables = [grist for grist in self.grists if grist.comparable]
        if not comparables:
            raise CobConsistencyError(fo(f"""
                Cannot compare Cob '{self.model.__name__}' objects because
                none of its grains are marked as comparable.
                To enable comparison, set comparable=True on at least one grain."""))
        return comparables

    # dict-like methods
    def items(self) -> Iterator[tuple[str, Any]]:
        """Yield ``(label, value)`` for active grists."""
        for grist in self.active_grists:
            yield grist.label, grist.get_value()

    def keys(self) -> Iterator[str]:
        """Yield labels of active grists."""
        for grist in self.active_grists:
            yield grist.label

    def clear(self) -> None:
        """Remove all values from the cob."""
        for grist in self.active_grists:
            del self.cob[grist.label]

    # def copy(self) -> "Cob":  # type: ignore
    #     """Create a shallow copy of the Cob."""
    #     raise NotImplementedError(fo(f"""
    #         The 'copy' method is not implemented yet for Cob objects."""))

    # def fromkeys(self, seq: Sequence[str], value: Any) -> "Cob":
    #     """That function that no one uses."""
    #     dikt: dict[str, Any] = {}
    #     for key in seq:
    #         dikt[key] = value
    #     return self.model(**dikt)

    def get(self, key: str, default: Any = ABSENT) -> Any:
        """Return value for ``key`` if present, else ``default``.

        If ``default`` is omitted and the key is unknown, model-level validation
        may raise an error.
        """
        grist = self.get_grist(key, default=None)
        if default is ABSENT and grist is None:
            raise KeyError(fo(f"""
                The key '{key}' does not exist in the Cob '{self.model.__name__}'."""))
        if grist is None or not grist.attr_exists():
            return default
        return grist.get_value()

    def pop(self, key: str, default: Any = ABSENT) -> Any:
        """Remove ``key`` and return its value.

        Args:
            key: BaseGrain label to remove.
            default: Fallback value when key does not exist.
        """
        if key in self.labels:
            value = self.cob[key]
            del self.cob[key]
            return value
        if default is ABSENT:
            raise KeyError(fo(f"""
                The key '{key}' does not exist in the cob."""))
        return default

    def popitem(self) -> tuple[str, Any]:
        """Removes the key and value of last defined BaseGrain.

        Returns:
            A tuple of (key, value) of the removed attribute.
            Raises KeyError if the Cob is empty.
        """
        if not self.active_grists:
            raise KeyError(
                fo(f"""The Cob '{self.model.__name__}' is empty."""))
        last_grist = self.active_grists[-1]
        value = last_grist.get_value()  # Get value before deletion
        del self.cob[last_grist.label]
        return last_grist.label, value

    def setdefault(self, key: str, default: Any) -> Any:
        """Return existing value for ``key`` or store and return ``default``."""
        grist = self.get_grist(key, default=None)
        if grist and grist.attr_exists():
            return grist.get_value()
        self.cob[key] = default
        return default

    def update(self,
               other: Mapping[str, Any] | Iterable[tuple[Any, Any]] | Sentinel = ABSENT,
               /,
               **kwargs: Any) -> None:
        """Update multiple values from a mapping/iterable and keyword pairs."""
        if other is not ABSENT:
            if type(other) is dict:
                for key in other.keys():
                    self.cob[key] = other[key]
            else:
                for key, value in other:
                    self.cob[key] = value
        for key, value in kwargs.items():
            self.cob[key] = value

    def values(self) -> Iterator[Any]:
        """Yield values of active grists."""
        for grist in self.active_grists:
            yield grist.get_value()


def create_dna_class(model: type["Cob"]) -> type[BaseDna]:
    """Create and initialize a dedicated DNA subclass for ``model``."""
    class Dna(BaseDna):
        pass
    Dna.__setup__(model)
    return Dna
